<?php
declare( strict_types=1 );

namespace Phpmystic\Liqx;

use Phpmystic\Liqx\Expr;
use Phpmystic\Liqx\Expr\ArrayLit;
use Phpmystic\Liqx\Expr\ArrowFunction;
use Phpmystic\Liqx\Expr\Binary;
use Phpmystic\Liqx\Expr\BlockBody;
use Phpmystic\Liqx\Expr\Call;
use Phpmystic\Liqx\Expr\Conditional;
use Phpmystic\Liqx\Expr\Filtered;
use Phpmystic\Liqx\Expr\Identifier;
use Phpmystic\Liqx\Expr\Literal;
use Phpmystic\Liqx\Expr\Logical;
use Phpmystic\Liqx\Expr\Member;
use Phpmystic\Liqx\Expr\ObjectLit;
use Phpmystic\Liqx\Expr\TemplateString;
use Phpmystic\Liqx\Expr\Unary;
use Phpmystic\Liqx\Node\Document;
use Phpmystic\Liqx\Node\Element;
use Phpmystic\Liqx\Node\Frontmatter;
use Phpmystic\Liqx\Node\FrontmatterDestructure;
use Phpmystic\Liqx\Node\Output;
use Phpmystic\Liqx\Node\Script;
use Phpmystic\Liqx\Node\Style;
use Phpmystic\Liqx\Node\Text;

/**
 * Emits a native PHP closure that renders a Document straight to a string —
 * no AST walking at runtime. The generated source is saved as a `.php` file
 * so OPcache compiles it to bytecode once and serves it from shared memory.
 *
 * All expression semantics (loose equality, truthiness, property lookup,
 * method dispatch, filters) are delegated to the same {@see Evaluator} helpers
 * the interpreter uses, so the two paths cannot drift. Only the *structure* —
 * the per-node/per-expression dispatch — is compiled away.
 */
final class Compiler {

	/**
	 * Bump when the emitter changes so existing cache artifacts (whose keys
	 * derive from the source hash alone) recompile instead of serving stale
	 * PHP.
	 */
	public const VERSION = 2;

	/**
	 * HTML void elements that must not have closing tags — mirrors the
	 * Renderer so compiled markup matches interpreted markup.
	 *
	 * @var array<string, bool>
	 */
	private const VOID_ELEMENTS = [
		'area'   => true,
		'base'   => true,
		'br'     => true,
		'col'    => true,
		'embed'  => true,
		'hr'     => true,
		'img'    => true,
		'input'  => true,
		'link'   => true,
		'meta'   => true,
		'param'  => true,
		'source' => true,
		'track'  => true,
		'wbr'    => true,
	];

	/**
	 * Compile-time scope stack. Each entry maps a bound name to its local
	 * variable name (no `$` prefix). Arrow parameters and block-body constants
	 * bind to real PHP locals inside their closure, so runtime iteration never
	 * pushes/pops Context scopes — the biggest win over the interpreter.
	 *
	 * @var list<array<string, string>>
	 */
	private array $scopeStack = [];

	/**
	 * Position within {@see $scopeStack} where the innermost closure's own
	 * bindings begin. A name resolved from a shallower index comes from an
	 * enclosing closure and must be captured via `use`.
	 */
	private int $closureStart = 0;

	/**
	 * Local variables (no `$` prefix) the innermost closure references from
	 * enclosing closures — becomes its `use (...)` list. Transiently reset by
	 * {@see arrow()}.
	 *
	 * @var array<string, bool>
	 */
	private array $captures = [];

	/**
	 * Global counter making local variable names unique across the whole
	 * generated source, so captured names collide with nothing.
	 */
	private int $varCounter = 0;

	private function freshVar(): string {
		return '__v' . ( $this->varCounter++ );
	}

	/**
	 * @return array{string, int}|null [local variable name (no `$` prefix), scope index]
	 */
	private function resolveBound( string $name ): ?array {
		for ( $i = count( $this->scopeStack ) - 1; $i >= 0; $i-- ) {
			if ( isset( $this->scopeStack[ $i ][ $name ] ) ) {
				return [ $this->scopeStack[ $i ][ $name ], $i ];
			}
		}

		return null;
	}

	private function bindLocal( string $name, string $var ): void {
		$this->scopeStack[ count( $this->scopeStack ) - 1 ][ $name ] = $var;
	}

	public function compile( Document $document ): string {
		$lines = [];

		$lines[] = '<?php';
		$lines[] = 'declare(strict_types=1);';
		$lines[] = '';
		$lines[] = '// Generated by Phpmystic\\Liqx\\Compiler — do not edit.';
		$lines[] = 'return static function ( \\Phpmystic\\Liqx\\Context $ctx, \\Phpmystic\\Liqx\\Evaluator $eval ): string {';
		$lines[] = "    \$out = '';";
		$lines[] = '    $ctx->push();';
		$lines[] = '    try {';

		foreach ( $document->frontmatter as $declaration ) {
			foreach ( $this->declarationLines( $declaration ) as $line ) {
				$lines[] = '        ' . $line;
			}
		}

		foreach ( $this->nodeStatements( $document->body, '        ' ) as $statement ) {
			$lines[] = $statement;
		}

		$lines[] = '    } finally {';
		$lines[] = '        $ctx->pop();';
		$lines[] = '    }';
		$lines[] = '';
		$lines[] = '    return $out;';
		$lines[] = '};';

		return implode( "\n", $lines );
	}

	// ---------------------------------------------------------------------
	// Declarations
	// ---------------------------------------------------------------------

	/**
	 * @return list<string> PHP statements (no trailing semicolon)
	 */
	private function declarationLines( Frontmatter|FrontmatterDestructure $declaration ): array {
		if ( $declaration instanceof FrontmatterDestructure ) {
			$lines = [ '$__src = ' . $this->expr( $declaration->init ) . ';' ];

			foreach ( $declaration->bindings as $binding ) {
				$default = null !== $binding['default'] ? $this->expr( $binding['default'] ) : 'null';
				$lines[] = '$ctx->set( '
					. var_export( $binding['name'], true )
					. ', ( ( $__hit = $eval->lookupProperty( $__src, ' . var_export( $binding['name'], true ) . ' ) )[\'found\'] ? $__hit[\'value\'] : ' . $default . ' ) );';
			}

			return $lines;
		}

		return [ '$ctx->set( ' . var_export( $declaration->name, true ) . ', ' . $this->expr( $declaration->expr ) . ' );' ];
	}

	/**
	 * Block-body declarations bind to closure-local variables instead of the
	 * Context — no scope push/pop per invocation. Each name is resolved and
	 * bound in order, so a later declaration shadows an earlier one and
	 * initializers can reference previously-declared locals.
	 *
	 * @return list<string> PHP statements (each carrying its trailing `;`)
	 */
	private function declarationLinesLocals( Frontmatter|FrontmatterDestructure $declaration ): array {
		if ( $declaration instanceof FrontmatterDestructure ) {
			$srcVar = $this->freshVar();
			$init   = $this->expr( $declaration->init );
			$lines  = [ '( $' . $srcVar . ' = ' . $init . ' );' ];

			foreach ( $declaration->bindings as $binding ) {
				$default = null !== $binding['default'] ? $this->expr( $binding['default'] ) : 'null';
				$var     = $this->freshVar();

				$this->bindLocal( $binding['name'], $var );

				$lines[] = '( $' . $var . ' = ( ( $__hit = $eval->lookupProperty( $' . $srcVar . ', ' . var_export( $binding['name'], true ) . ' ) )[\'found\'] ? $__hit[\'value\'] : ' . $default . ' ) );';
			}

			return $lines;
		}

		$init = $this->expr( $declaration->expr );
		$var  = $this->freshVar();

		$this->bindLocal( $declaration->name, $var );

		return [ '( $' . $var . ' = ' . $init . ' );' ];
	}

	// ---------------------------------------------------------------------
	// Nodes
	// ---------------------------------------------------------------------

	/**
	 * A flat list of `$out .= <expr>;` statements, merging adjacent text.
	 *
	 * @param list<\Phpmystic\Liqx\Node> $nodes
	 * @return list<string>
	 */
	private function nodeStatements( array $nodes, string $indent ): array {
		$statements = [];
		$text       = '';

		foreach ( $nodes as $node ) {
			if ( $node instanceof Text ) {
				$text .= $node->value;

				continue;
			}

			if ( '' !== $text ) {
				$statements[] = $indent . '$out .= ' . var_export( $text, true ) . ';';
				$text         = '';
			}

			$statements[] = $indent . '$out .= ' . $this->node( $node ) . ';';
		}

		if ( '' !== $text ) {
			$statements[] = $indent . '$out .= ' . var_export( $text, true ) . ';';
		}

		return $statements;
	}

	/**
	 * A parenthesized PHP expression producing this node's markup.
	 */
	private function node( object $node ): string {
		if ( $node instanceof Text ) {
			return '(' . var_export( $node->value, true ) . ')';
		}

		if ( $node instanceof Output ) {
			return $this->renderValue( $this->expr( $node->expr ) );
		}

		if ( $node instanceof Element ) {
			return $this->element( $node );
		}

		if ( $node instanceof Style ) {
			return $this->style( $node );
		}

		if ( $node instanceof Script ) {
			return $this->script( $node );
		}

		throw new LiqxException( 'Cannot compile node ' . $node::class );
	}

	private function element( Element $element ): string {
		$tag = var_export( $element->tag, true );

		if ( $element->selfClosing ) {
			if ( isset( self::VOID_ELEMENTS[ strtolower( $element->tag ) ] ) ) {
				return "( '<' . {$tag} . " . $this->attrs( $element->attrs ) . " . ' />' )";
			}

			return "( '<' . {$tag} . " . $this->attrs( $element->attrs ) . " . '></' . {$tag} . '>' )";
		}

		return "( '<' . {$tag} . " . $this->attrs( $element->attrs ) . " . '>' . " . $this->children( $element->children ) . " . '</' . {$tag} . '>' )";
	}

	/**
	 * @param list<array{name:string|null, value:Expr|null, spread:bool}> $attrs
	 */
	private function attrs( array $attrs ): string {
		$parts = [];

		foreach ( $attrs as $attr ) {
			[ 'name' => $name, 'value' => $value, 'spread' => $spread ] = $attr;

			if ( null === $name ) {
				if ( null === $value ) {
					throw new LiqxException( 'Compile error: attribute without a name and without a value' );
				}

				$parts[] = $spread
					? '$eval->spreadAttrs( ' . $this->expr( $value ) . ' )'
					: '$eval->stringify( ' . $this->expr( $value ) . ' )';

				continue;
			}

			if ( 'key' === $name ) {
				continue;
			}

			if ( null === $value ) {
				$parts[] = var_export( ' ' . $name, true );

				continue;
			}

			$parts[] = '$eval->attribute( ' . var_export( $name, true ) . ', ' . $this->expr( $value ) . ' )';
		}

		if ( [] === $parts ) {
			return "( '' )";
		}

		return '( ' . implode( ' . ', $parts ) . ' )';
	}

	/**
	 * @param list<\Phpmystic\Liqx\Node> $children
	 */
	private function children( array $children ): string {
		$parts = [];

		foreach ( $children as $child ) {
			if ( $child instanceof Text ) {
				$parts[] = var_export( $child->value, true );
			} else {
				$parts[] = $this->node( $child );
			}
		}

		if ( [] === $parts ) {
			return "( '' )";
		}

		return '( ' . implode( ' . ', $parts ) . ' )';
	}

	/**
	 * @param list<string|Expr> $parts
	 */
	private function verbatimParts( array $parts, string $fallbackBody ): string {
		if ( [] === $parts ) {
			return '(' . var_export( $fallbackBody, true ) . ')';
		}

		$compiled = [];

		foreach ( $parts as $part ) {
			$compiled[] = is_string( $part )
				? var_export( $part, true )
				: $this->renderValue( $this->expr( $part ) );
		}

		return '(' . implode( ' . ', $compiled ) . ')';
	}

	private function style( Style $node ): string {
		return "( '<style>' . " . $this->verbatimParts( $node->parts, $node->body ) . " . '</style>' )";
	}

	private function script( Script $node ): string {
		return "( '<script' . " . $this->attrs( $node->attrs ) . " . '>' . " . $this->verbatimParts( $node->parts, $node->body ) . " . '</script>' )";
	}

	private function renderValue( string $expr ): string {
		return '$eval->renderValue( ' . $expr . ', $ctx )';
	}

	// ---------------------------------------------------------------------
	// Expressions
	// ---------------------------------------------------------------------

	/**
	 * Compile an expression to a parenthesized PHP expression. `$lenient`
	 * disables strict identifier lookups — used for the left side of `??`,
	 * where the interpreter suppresses undefined-variable errors.
	 */
	private function expr( Expr $expression, bool $lenient = false ): string {
		if ( $expression instanceof Literal ) {
			return '(' . var_export( $expression->value, true ) . ')';
		}

		if ( $expression instanceof Identifier ) {
			$resolved = $this->resolveBound( $expression->name );

			if ( null !== $resolved ) {
				[ $var, $index ] = $resolved;

				if ( $index < $this->closureStart ) {
					$this->captures[ $var ] = true;
				}

				return '( $' . $var . ' )';
			}

			return $lenient
				? '( $ctx->get( ' . var_export( $expression->name, true ) . ' ) )'
				: '( ( $ctx->strict ? $eval->identifier( $ctx, ' . var_export( $expression->name, true ) . ' ) : $ctx->get( ' . var_export( $expression->name, true ) . ' ) ) )';
		}

		if ( $expression instanceof Member ) {
			$object = $this->expr( $expression->object, $lenient );

			if ( $expression->computed ) {
				if ( ! $expression->access instanceof Expr ) {
					throw new LiqxException( 'Compile error: computed member access is not an expression' );
				}

				$key = $this->expr( $expression->access, $lenient );
			} else {
				$key = var_export( (string) $expression->access, true );
			}

			return '( $eval->getProperty( ' . $object . ', ' . $key . ' ) )';
		}

		if ( $expression instanceof Call ) {
			return $this->call( $expression, $lenient );
		}

		if ( $expression instanceof ArrayLit ) {
			$elements = array_map( fn ( Expr $e ) => $this->expr( $e, $lenient ), $expression->elements );

			return '( [ ' . implode( ', ', $elements ) . ' ] )';
		}

		if ( $expression instanceof ObjectLit ) {
			$properties = array_map(
				fn ( array $property ) => var_export( $property[0], true ) . ' => ' . $this->expr( $property[1], $lenient ),
				$expression->properties
			);

			return '( [ ' . implode( ', ', $properties ) . ' ] )';
		}

		if ( $expression instanceof Binary ) {
			return $this->binary( $expression, $lenient );
		}

		if ( $expression instanceof Logical ) {
			return $this->logical( $expression, $lenient );
		}

		if ( $expression instanceof Unary ) {
			$operand = $this->expr( $expression->operand, $lenient );

			return match ( $expression->op ) {
				'!' => '( ! $eval->truthy( ' . $operand . ' ) )',
				'-' => '( - $eval->toNumber( ' . $operand . ' ) )',
				'+' => '( $eval->toNumber( ' . $operand . ' ) )',
				default => throw new LiqxException( 'Unknown unary operator ' . $expression->op ),
			};
		}

		if ( $expression instanceof Conditional ) {
			return '( $eval->truthy( ' . $this->expr( $expression->test, $lenient ) . ' ) ? ' . $this->expr( $expression->consequent, $lenient ) . ' : ' . $this->expr( $expression->alternate, $lenient ) . ' )';
		}

		if ( $expression instanceof ArrowFunction ) {
			return $this->arrow( $expression, $lenient );
		}

		if ( $expression instanceof BlockBody ) {
			// Only reachable as an arrow body; the grammar never produces a
			// bare block body in expression position.
			throw new LiqxException( 'A block body cannot be compiled outside an arrow function' );
		}

		if ( $expression instanceof TemplateString ) {
			$parts = [];

			foreach ( $expression->parts as $part ) {
				$parts[] = is_string( $part )
					? var_export( $part, true )
					: $this->expr( $part, $lenient );
			}

			return '( $eval->templateString( [ ' . implode( ', ', $parts ) . ' ], $ctx ) )';
		}

		if ( $expression instanceof Filtered ) {
			return $this->filtered( $expression, $lenient );
		}

		if ( $expression instanceof Element ) {
			return $this->element( $expression );
		}

		if ( $expression instanceof Style ) {
			return $this->style( $expression );
		}

		if ( $expression instanceof Script ) {
			return $this->script( $expression );
		}

		throw new LiqxException( 'Cannot compile expression node ' . $expression::class );
	}

	/**
	 * @param list<Expr> $args
	 */
	private function argList( array $args, bool $lenient ): string {
		$compiled = array_map( fn ( Expr $arg ) => $this->expr( $arg, $lenient ), $args );

		return implode( ', ', $compiled );
	}

	private function call( Call $expression, bool $lenient ): string {
		$args   = $this->argList( $expression->args, $lenient );
		$callee = $expression->callee;

		if ( $callee instanceof Member ) {
			$object = $this->expr( $callee->object, $lenient );

			return '( $eval->methodCall( ' . $object . ', ' . var_export( (string) $callee->access, true ) . ', [ ' . $args . ' ], $ctx ) )';
		}

		if ( $callee instanceof Identifier ) {
			return '( $eval->callNamed( $ctx, ' . var_export( $callee->name, true ) . ', [ ' . $args . ' ] ) )';
		}

		return '( $eval->invoke( ' . $this->expr( $callee, $lenient ) . ', [ ' . $args . ' ], $ctx ) )';
	}

	private function binary( Binary $expression, bool $lenient ): string {
		$left  = $this->expr( $expression->left, $lenient );
		$right = $this->expr( $expression->right, $lenient );

		return match ( $expression->op ) {
			'+'   => '( ( is_string( ' . $left . ' ) || is_string( ' . $right . ' ) ) ? ( (string) ' . $left . ' . (string) ' . $right . ' ) : ( $eval->toNumber( ' . $left . ' ) + $eval->toNumber( ' . $right . ' ) ) )',
			'-'   => '( $eval->toNumber( ' . $left . ' ) - $eval->toNumber( ' . $right . ' ) )',
			'*'   => '( $eval->toNumber( ' . $left . ' ) * $eval->toNumber( ' . $right . ' ) )',
			'/'   => '( $eval->toNumber( ' . $left . ' ) / $eval->toNumber( ' . $right . ' ) )',
			'%'   => '( $eval->toNumber( ' . $left . ' ) % $eval->toNumber( ' . $right . ' ) )',
			'=='  => '( $eval->looseEqual( ' . $left . ', ' . $right . ' ) )',
			'!='  => '( ! $eval->looseEqual( ' . $left . ', ' . $right . ' ) )',
			'===' => '( ' . $left . ' === ' . $right . ' )',
			'!==' => '( ' . $left . ' !== ' . $right . ' )',
			'<'   => '( $eval->compare( ' . $left . ', ' . $right . ' ) < 0 )',
			'>'   => '( $eval->compare( ' . $left . ', ' . $right . ' ) > 0 )',
			'<='  => '( $eval->compare( ' . $left . ', ' . $right . ' ) <= 0 )',
			'>='  => '( $eval->compare( ' . $left . ', ' . $right . ' ) >= 0 )',
			default => throw new LiqxException( 'Unknown operator ' . $expression->op ),
		};
	}

	private function logical( Logical $expression, bool $lenient ): string {
		$left  = $this->expr( $expression->left, $lenient );
		$right = $this->expr( $expression->right, $lenient );

		if ( '??' === $expression->op ) {
			// The interpreter evaluates the left side leniently — a missing
			// variable collapses to null instead of throwing.
			$lenientLeft = $this->expr( $expression->left, true );

			return '( ( ' . $lenientLeft . ' === null ) ? ' . $right . ' : ' . $lenientLeft . ' )';
		}

		if ( '||' === $expression->op ) {
			return '( $eval->truthy( ' . $left . ' ) ? ' . $left . ' : ' . $right . ' )';
		}

		return '( $eval->truthy( ' . $left . ' ) ? ' . $right . ' : ' . $left . ' )';
	}

	private function filtered( Filtered $expression, bool $lenient ): string {
		$pipeline = [];

		foreach ( $expression->filters as $filter ) {
			$args      = $this->argList( $filter->args, $lenient );
			$pipeline[] = '[ ' . var_export( $filter->name, true ) . ', [ ' . $args . ' ] ]';
		}

		return '( $eval->filtered( ' . $this->expr( $expression->value, $lenient ) . ', [ ' . implode( ', ', $pipeline ) . ' ], $ctx ) )';
	}

	/**
	 * An arrow function becomes a real PHP closure whose parameters bind to
	 * closure-local variables — no Context scope push/pop per invocation.
	 * Constants and destructure bindings from a block body also become locals.
	 * Any local referenced from an enclosing closure is captured via `use`.
	 */
	private function arrow( ArrowFunction $expression, bool $lenient ): string {
		$savedClosureStart = $this->closureStart;
		$savedCaptures     = $this->captures;

		$paramLines = [];
		$bindings   = [];

		foreach ( $expression->params as $index => $param ) {
			$var             = $this->freshVar();
			$bindings[ $param ] = $var;
			$paramLines[]    = '    $' . $var . ' = $__args[' . $index . '] ?? null;';
		}

		$this->scopeStack[]  = $bindings;
		$this->closureStart  = count( $this->scopeStack ) - 1;
		$this->captures      = [];

		$bodyLines = [];

		if ( $expression->body instanceof BlockBody ) {
			foreach ( $expression->body->declarations as $declaration ) {
				foreach ( $this->declarationLinesLocals( $declaration ) as $statement ) {
					$bodyLines[] = '        ' . $statement;
				}
			}

			$bodyLines[] = $expression->body->return !== null
				? '        return ' . $this->expr( $expression->body->return, $lenient ) . ';'
				: '        return null;';
		} else {
			$bodyLines[] = '        return ' . $this->expr( $expression->body, $lenient ) . ';';
		}

		array_pop( $this->scopeStack );
		$this->closureStart = $savedClosureStart;
		$this->captures     = $savedCaptures;

		$lines   = [];
		$use     = 'use ( $ctx, $eval';

		foreach ( array_keys( $this->captures ) as $useVar ) {
			$use .= ', $' . $useVar;
		}

		$use     .= ' )';
		$lines[] = 'static function ( mixed ...$__args ) ' . $use . ' {';
		$lines[] = implode( "\n", $paramLines );

		foreach ( $bodyLines as $bodyLine ) {
			$lines[] = $bodyLine;
		}

		$lines[] = '}';

		return '(' . implode( "\n", $lines ) . ')';
	}
}